application: hostel-dev
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

builtins:
- datastore_admin: on

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /media
  static_dir: _generated_media
  secure: optional

- url: /media2
  static_dir: static/images

- url: /media2/(.*)
  static_files: media2/\1
  upload: media2/(.*)



- url: /.*
  script: common/appenginepatch/main.py
  secure: optional
